version: '3'
services:
  centos:
    build: ./centos
    image: centos
    container_name: centos
    ports: 
      - 8080:80
      - 8443:443
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
